name: Linux

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build Linux
      run: ./make.sh all
